name: Tauri (Yew) Build & Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package lists
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libglib2.0-dev libpango1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libatk1.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libsoup-3.0-dev
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk
      - name: Build Cargo dependencies
        run: cargo build --release
      - name: Build Yew app
        run: trunk build --release
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Build Tauri app
        run: cargo tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: millmill
          path: src-tauri/target/release/bundle/

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: millmill
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
